tag existence check

diff --git a/.github/workflows/deploy-extension-to-marketplace.yml b/.github/workflows/deploy-extension-to-marketplace.yml
--- a/.github/workflows/deploy-extension-to-marketplace.yml
+++ b/.github/workflows/deploy-extension-to-marketplace.yml
@@ -108,34 +108,34 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_MP_ACCESS_KEY_ID }}
           aws-region: us-east-1
 
-      - name: Check if ECR image tag exists
-        id: check_tag
-        run: |
-          TAG_EXISTS=false
-          TAG_CHECK=$(aws ecr describe-images \
-              --registry-id ${{ secrets.REGISTRY_ID }} \
-              --repository-name ${{ secrets.ECR_REPOSITORY }} \
-              --region us-east-1 \
-              --image-ids imageTag=${{ github.event.inputs.docker_tag }} \
-              --query 'imageIds[*].imageTag' --output text || true)
-          
-          if [[ "$TAG_CHECK" == "${{ github.event.inputs.docker_tag }}" ]]; then
-              echo "Error: Tag '${{ github.event.inputs.docker_tag }}' already exists."
-              TAG_EXISTS=true
-          fi
-          
-          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_ENV
+#      - name: Check if ECR image tag exists
+#        id: check_tag
+#        run: |
+#          TAG_EXISTS=false
+#          TAG_CHECK=$(aws ecr describe-images \
+#              --registry-id ${{ secrets.REGISTRY_ID }} \
+#              --repository-name ${{ secrets.ECR_REPOSITORY }} \
+#              --region us-east-1 \
+#              --image-ids imageTag=${{ github.event.inputs.docker_tag }} \
+#              --query 'imageIds[*].imageTag' --output text || true)
+#
+#          if [[ "$TAG_CHECK" == "${{ github.event.inputs.docker_tag }}" ]]; then
+#              echo "Error: Tag '${{ github.event.inputs.docker_tag }}' already exists."
+#              TAG_EXISTS=true
+#          fi
+#
+#          echo "TAG_EXISTS=$TAG_EXISTS" >> $GITHUB_ENV
 
       - name: Build Docker image
-        if: env.TAG_EXISTS == false
+#        if: env.TAG_EXISTS == false
         run: docker build -t ${{ secrets.AWS_MP_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.event.inputs.docker_tag }} .
 
       - name: Push to Docker AWS MP
-        if: env.TAG_EXISTS == false
+#        if: env.TAG_EXISTS == false
         run: docker push ${{ secrets.AWS_MP_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.event.inputs.docker_tag }}
 
       - name: Submit Request for AWS MP Listing
-        if: env.TAG_EXISTS == false
+#        if: env.TAG_EXISTS == false
         env:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: ${{ github.event.inputs.docker_tag }}
